@echo off
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas50\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas51\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas52\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas53\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas54\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas55\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas56\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas57\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas58\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas59\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas60\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas61\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas62\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas63\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas64\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas65\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas66\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas67\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas68\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas69\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas70\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas71\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas72\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas73\Sistemas\Temp
xcopy /b C:\Users\estudiante\Documents\John\fileTransfer\src \\Sistemas74\Sistemas\Temp
